name: 'Toolbox example'
description: 'Toolbox hello world'
inputs:
  who_to_greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'Default from action.yml'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who_to_greet }}
